spring:
  application:
    name: spring-deepl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://192.168.100.135:3306/ai_chat
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariPool-1
  jpa:
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  elasticsearch:
    uris: http://192.168.103.176:9200
  ai:
    ollama:
      base-url: http://192.168.103.176:11434
      chat:
        model: deepseek-r1
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: knowledge_base
        dimensions: 768
        similarity: cosine

logging:
  level:
    '[org.springframework.ai.chat]': DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
